<?php
declare(strict_types=1);

/**
 * CM Free / CM Plus / CM PRO - CM Bridge Protocol v1
 * File: admin/api/bridge/v1/pairing/exchange.php
 * Author: Viljem Dvojmoč
 * Assistant: Claude
 * Copyright (c) 2026 Viljem Dvojmoč. All rights reserved.
 *
 * Exchanges a one-time pairing code (generated by admin/api/pairing_generate.php)
 * for a permanent per-device token. Deliberately NOT behind
 * cm_bridge_require_auth() - the code itself is the one-shot credential
 * for this single call, same reasoning as any OAuth-style code exchange.
 * See CM Companion's bridge/PairingExchange.kt for the client side of
 * this exact contract.
 */

require_once __DIR__ . '/../../../../../common/lib/cm_bridge_pairing.php';

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'POST') {
    http_response_code(405);
    echo json_encode(['ok' => false, 'error' => 'method_not_allowed'], JSON_UNESCAPED_UNICODE);
    exit;
}

$body = json_decode((string)file_get_contents('php://input'), true);
if (!is_array($body)) {
    http_response_code(400);
    echo json_encode(['ok' => false, 'error' => 'invalid_json_body'], JSON_UNESCAPED_UNICODE);
    exit;
}

$installationId = trim((string)($body['installation_id'] ?? ''));
$code = trim((string)($body['code'] ?? ''));
$deviceLabel = trim((string)($body['device_label'] ?? ''));

if ($installationId === '' || $code === '') {
    http_response_code(400);
    // Split, not one combined "missing_installation_id_or_code" - a
    // real debugging session (2026-09-02/03) showed a generic combined
    // message makes it impossible to tell which of the two empty fields
    // is the actual problem from the client side alone.
    echo json_encode([
        'ok' => false,
        'error' => $installationId === '' ? 'missing_installation_id' : 'missing_code',
    ], JSON_UNESCAPED_UNICODE);
    exit;
}

$result = cm_bridge_pairing_exchange($installationId, $code, $deviceLabel);
if (empty($result['ok'])) {
    http_response_code(401);
} else {
    // Server-side connection counter, bumped only on an actual successful
    // exchange (not on every button tap the way companion_pairing_click
    // is) - lives in the same page_counters.json the public landing page
    // already reads via api/counter.php, so stats.php on GN7 can show a
    // real "how many phones have paired" number without a new endpoint.
    $countersFile = __DIR__ . '/../../../../../data/page_counters.json';
    $fp = @fopen($countersFile, 'c+');
    if ($fp !== false) {
        flock($fp, LOCK_EX);
        $raw = stream_get_contents($fp);
        $data = ($raw !== false && $raw !== '') ? json_decode($raw, true) : null;
        if (!is_array($data)) {
            $data = [];
        }
        $data['companion_connections_total'] = (int)($data['companion_connections_total'] ?? 0) + 1;
        ftruncate($fp, 0);
        rewind($fp);
        fwrite($fp, json_encode($data, JSON_PRETTY_PRINT));
        fflush($fp);
        flock($fp, LOCK_UN);
        fclose($fp);
    }
}
echo json_encode($result, JSON_UNESCAPED_UNICODE);
